In [118]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [119]:
data=pd.read_csv('mail_data.csv')

In [120]:
data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [121]:
data.isnull().sum()

Category    0
Message     0
dtype: int64

In [122]:
data.shape

(5572, 2)

In [123]:
# Label encoding -> spam-0 and ham-1
data.loc[data['Category']=='spam', 'Category']=0
data.loc[data['Category']=='ham', 'Category']=1

In [124]:
X=data['Message']
Y=data['Category']

In [125]:
X_train, X_test, Y_train, Y_test = train_test_split(
    X, Y, test_size=0.2, random_state=2
)

In [126]:
print(X.shape,X_train.shape,X_test.shape)

(5572,) (4457,) (1115,)

In [127]:
from sklearn import feature_extraction
feature_extraction=TfidfVectorizer(min_df=1,stop_words='english', lowercase=True)
X_train_features=feature_extraction.fit_transform(X_train)
X_test_features=feature_extraction.transform(X_test)

In [128]:
Y_train=Y_train.astype('int')
Y_test=Y_test.astype('int')

In [129]:
X_train

3890                    Unlimited texts. Limited minutes.
5553                          Hahaha..use your brain dear
4366    Ujhhhhhhh computer shipped out with address to...
3968    YOU HAVE WON! As a valued Vodafone customer ou...
3771    Love it! The girls at the office may wonder wh...
                              ...
3335    That's fine, have him give me a call if he kno...
1099    NO GIFTS!! You trying to get me to throw mysel...
2514    U have won a nokia 6230 plus a free digital ca...
3606                      Jordan got voted out last nite!
2575    Your next amazing xxx PICSFREE1 video will be ...
Name: Message, Length: 4457, dtype: object

In [130]:
print(X_train_features)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 34768 stored elements and shape (4457, 7458)>
  Coords	Values
  (0, 6927)	0.48935591439341625
  (0, 6586)	0.44333254982109394
  (0, 3958)	0.6161071828926097
  (0, 4334)	0.42941702167641554
  (1, 3168)	0.5869421390016224
  (1, 6971)	0.4281243465155688
  (1, 1428)	0.5869421390016224
  (1, 2121)	0.35736171430221464
  (2, 6878)	0.35749230587184955
  (2, 1876)	0.28751725124107325
  (2, 5894)	0.35749230587184955
  (2, 806)	0.26730249393705324
  (2, 5695)	0.35749230587184955
  (2, 4884)	0.35749230587184955
  (2, 3852)	0.3408491178137899
  (2, 7353)	0.31988118061968496
  (2, 5115)	0.3408491178137899
  (3, 1876)	0.3080768784015236
  (3, 7297)	0.22192369472149484
  (3, 7000)	0.30072945056088285
  (3, 7065)	0.32795623716393424
  (3, 2060)	0.24915048132454623
  (3, 5005)	0.3169028431039865
  (3, 7248)	0.23571908490908416
  (3, 300)	0.2915969875465198
  :	:
  (4454, 4627)	0.3831814754124698
  (4454, 311)	0.19547195974237946
  (4454, 5068)	0.22284357632450164
  (4454, 1094)	0.24862733340971144
  (4454, 1575)	0.20946314330145205
  (4454, 666)	0.28653660324238944
  (4454, 2244)	0.2526916142542512
  (4454, 7084)	0.2689097965804433
  (4454, 571)	0.3005277868014621
  (4454, 5077)	0.3005277868014621
  (4454, 297)	0.3005277868014621
  (4455, 3084)	0.3019392955127119
  (4455, 4614)	0.4677148905542796
  (4455, 3701)	0.546620099025937
  (4455, 7075)	0.6255253074975946
  (4456, 6575)	0.15362974460832007
  (4456, 5820)	0.18767970267638426
  (4456, 7376)	0.20404881687716278
  (4456, 7033)	0.43304344994724825
  (4456, 380)	0.24893867331233713
  (4456, 2509)	0.20620887737471993
  (4456, 7032)	0.2868954144677231
  (4456, 909)	0.26924653489772427
  (4456, 5009)	0.6018082365591317
  (4456, 3768)	0.30090411827956587

In [131]:
model=LogisticRegression()

In [132]:
model.fit(X_train_features,Y_train)

LogisticRegression()

In [133]:
prediction=model.predict(X_train_features)
accuracy=accuracy_score(Y_train,prediction)
print('accuracy on training data is:',accuracy)

accuracy on training data is: 0.9685887368184878

In [134]:
prediction=model.predict(X_test_features)
accuracy=accuracy_score(Y_test,prediction)
print('accuracy on testing data is:',accuracy)

accuracy on testing data is: 0.9533632286995516

In [135]:
# predicting the model
new_mail = ["WINNER!! As a valued network customer you have been selected to receivea Â£900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only."]

new_mail_features = feature_extraction.transform(new_mail)
prediction = model.predict(new_mail_features)

if prediction[0] == 0:
    print("\nThis is a Spam Mail")
else:
    print("\nThis is a Ham Mail")

This is a Spam Mail

In [136]:
# predicting the model
new_mail = ["Even my brother is not like to speak with me. They treat me like aids patent."]

new_mail_features = feature_extraction.transform(new_mail)
prediction = model.predict(new_mail_features)

if prediction[0] == 0:
    print("\nThis is a Spam Mail")
else:
    print("\nThis is a Ham Mail")

This is a Ham Mail